version = 0.1

[default.build.parameters]
use_container = false

[default.deploy.parameters]
stack_name = "serverless-matching-engine"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_image_repos = true
resolve_s3 = true
